### PR TITLE
Synchronization with Splatter

### PR DESCRIPTION
**Pull request by Txus5012**
For people who likes to see a lot of blood and have [Splatter](https://github.com/theripper93/Splatter) and Automatic Wounds modules, there are two blood colors to set.

This PR makes this module use Splatter's blood color (which is set in a token setting), so both modules can change colors at the same time. Automatic Wounds flag still takes precedence.

I also added a macro to revert to the default value (by removing Automatic Wounds blood-color flag).

### CODE REVIEW

**Comment by shemetz** [comment]
Nice! 
I don't like the new db file diffs, but, I guess I'll take them.

**Comment by shemetz** [comment]
I tried to continue this and create a release, but, I'm having issues with the packed database...

@Txus5012  could you please use the [foundryvtt-cli](https://github.com/foundryvtt/foundryvtt-cli) to unpack your database, re-pack it, add and commit the new files created inside `_source` along with all files inside the pack folder (including newly created files), and then create a PR with all of that?

I'll undo this merge for now.

**Comment by Txus5012** [comment]
I don't know how to use it. Maybe it's easier if you create the macro yourself?
The code is:

```
for ( const token of canvas.tokens.controlled )
 token.actor.unsetFlag("tokenmagic-automatic-wounds", "blood-color")
```

The change to tokenmagic-automatic-wounds.js is independent of the macro.

**Comment by shemetz** [comment]
Sure, will do, thanks!

**Pull request merged**
